"use client";

import { useEffect, useState, useTransition } from "react";
import type { Tables } from "@/lib/supabase/database.types";
import type { PersonSummary } from "@/lib/family";
import { PersonSearch } from "@/components/person-search";
import { CreateFamilyForm } from "@/components/create-family-form";
import { ForkFamilyForm } from "@/components/fork-family-form";
import { getVoicesAsync, pickPreferredVoice } from "@/lib/speech-voices";
import {
  setLinkedPerson,
  setInterviewVoice,
  setNarrationEnabled,
  createFamilyInvite,
  setActiveFamily,
} from "./actions";

type Person = Tables<"people">;
type FamilyMembership = { id: string; name: string; isActive: boolean };

export function SettingsView({
  people,
  personSummaries,
  linkedPersonId,
  interviewVoiceURI,
  narrationEnabled,
  families,
  emailUploadToken,
}: {
  people: Person[];
  personSummaries: Record<string, PersonSummary>;
  linkedPersonId: string | null;
  interviewVoiceURI: string | null;
  narrationEnabled: boolean;
  families: FamilyMembership[];
  emailUploadToken: string | null;
}) {
  return (
    <>
      {families.length > 1 && <FamilySwitcherSettings families={families} />}
      <ThisIsMeSettings
        people={people}
        personSummaries={personSummaries}
        linkedPersonId={linkedPersonId}
      />
      <EmailUploadSettings emailUploadToken={emailUploadToken} />
      <NarrationToggleSettings narrationEnabled={narrationEnabled} />
      <VoiceSettings interviewVoiceURI={interviewVoiceURI} />
      <InviteSettings />
      <CreateFamilySettings />
      <ForkFamilySettings />
    </>
  );
}

// Email-based upload, Stage 2: the address is per-family, already exists
// the moment the family does (families.email_upload_token — generated by
// a DB column default, see the Stage 1 migration), so unlike "Invite
// someone" above there's no generate step here, just a display. The
// subdomain (uploads.talkthroughhistory.com) is the one the Stage 1 DNS
// investigation recommended — a dedicated subdomain, isolated from the
// root domain's existing Mailtrap outbound/DMARC setup — and matches
// what the Worker's own README documents for its Email Routing catch-all
// rule. Not yet deployed (see cloudflare-worker/README.md), so this
// address doesn't receive real mail yet; showing it here now means it's
// already correct and visible the moment it does.
const EMAIL_UPLOAD_DOMAIN = "uploads.talkthroughhistory.com";

function EmailUploadSettings({ emailUploadToken }: { emailUploadToken: string | null }) {
  const [copied, setCopied] = useState(false);
  const address = emailUploadToken ? `${emailUploadToken}@${EMAIL_UPLOAD_DOMAIN}` : null;

  async function handleCopy() {
    if (!address) return;
    try {
      await navigator.clipboard.writeText(address);
      setCopied(true);
    } catch {
      // Clipboard access can be denied — the address is still shown and
      // selectable by hand, same fallback as the invite link's own copy
      // button above.
    }
  }

  return (
    <section className="flex flex-col gap-4 rounded-[var(--radius-lg)] border border-[color:var(--color-border)] bg-[color:var(--color-bg-surface)] p-6 shadow-[var(--shadow-2)]">
      <div>
        <h2 className="text-[length:var(--font-size-heading-3)] leading-[var(--line-height-heading-3)] font-semibold">
          Email upload address
        </h2>
        <p className="mt-1 text-sm text-[color:var(--color-text-secondary)]">
          Email photos or documents to this address and they&apos;ll be added automatically — no
          login needed. Forward it to anyone in the family.
        </p>
      </div>

      {address ? (
        <div className="flex flex-col gap-2">
          <input
            type="text"
            readOnly
            value={address}
            onFocus={(e) => e.currentTarget.select()}
            className="rounded-[var(--radius-sm)] border border-[color:var(--color-border)] bg-[color:var(--color-bg-page)] px-3 py-2 text-sm text-[color:var(--color-text-primary)]"
          />
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleCopy}
              className="rounded-[var(--radius-sm)] border border-[color:var(--color-border)] px-4 py-2 text-sm transition-colors duration-[var(--duration-base)] hover:bg-[color:var(--color-bg-surface-hover)]"
            >
              Copy address
            </button>
            {copied && (
              <span className="text-sm text-[color:var(--color-success-subtle-fg)]">Copied.</span>
            )}
          </div>
        </div>
      ) : (
        <p className="text-sm text-[color:var(--color-error)]">
          No upload address found for this family.
        </p>
      )}
    </section>
  );
}

// Available to any current family member, not just an "owner" role — the
// invite itself is single-use and expires, and its RLS/RPC scoping (see
// the family_invites migration) means it can only ever grant access to
// this same family, so there's no meaningful extra risk in letting any
// member generate one. Shows one link at a time rather than a running
// list of past invites — generating a fresh one for each person you
// invite is the expected flow, and this app doesn't yet have an
// invite-management view (revoking, seeing who's pending, etc.) to pair
// with a list.
function InviteSettings() {
  const [link, setLink] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  function handleGenerate() {
    setError(null);
    setCopied(false);
    startTransition(async () => {
      const result = await createFamilyInvite();
      if ("error" in result) {
        setError(result.error);
        return;
      }
      // Built client-side, same as the login page's own emailRedirectTo —
      // a server action has no reliable access to the request's own
      // origin without trusting a forwarded host header.
      setLink(`${window.location.origin}/join/${result.code}`);
    });
  }

  async function handleCopy() {
    if (!link) return;
    try {
      await navigator.clipboard.writeText(link);
      setCopied(true);
    } catch {
      // Clipboard access can be denied (permissions, non-HTTPS context,
      // etc.) — the link is still shown and selectable by hand, so this
      // failing isn't fatal, just skip the "Copied" confirmation.
    }
  }

  return (
    <section className="flex flex-col gap-4 rounded-[var(--radius-lg)] border border-[color:var(--color-border)] bg-[color:var(--color-bg-surface)] p-6 shadow-[var(--shadow-2)]">
      <div>
        <h2 className="text-[length:var(--font-size-heading-3)] leading-[var(--line-height-heading-3)] font-semibold">
          Invite someone
        </h2>
        <p className="mt-1 text-sm text-[color:var(--color-text-secondary)]">
          Generate a link that lets someone join this family tree. Each link works once and
          expires after 7 days.
        </p>
      </div>

      {link && (
        <div className="flex flex-col gap-2">
          <input
            type="text"
            readOnly
            value={link}
            onFocus={(e) => e.currentTarget.select()}
            className="rounded-[var(--radius-sm)] border border-[color:var(--color-border)] bg-[color:var(--color-bg-page)] px-3 py-2 text-sm text-[color:var(--color-text-primary)]"
          />
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleCopy}
              className="rounded-[var(--radius-sm)] border border-[color:var(--color-border)] px-4 py-2 text-sm transition-colors duration-[var(--duration-base)] hover:bg-[color:var(--color-bg-surface-hover)]"
            >
              Copy link
            </button>
            {copied && (
              <span className="text-sm text-[color:var(--color-success-subtle-fg)]">Copied.</span>
            )}
          </div>
        </div>
      )}

      {error && <p className="text-sm text-[color:var(--color-error)]">{error}</p>}

      <div>
        <button
          type="button"
          onClick={handleGenerate}
          disabled={isPending}
          className="rounded-[var(--radius-sm)] bg-[color:var(--color-accent)] px-4 py-2 text-sm font-medium text-[color:var(--color-text-on-accent)] transition-colors duration-[var(--duration-base)] hover:bg-[color:var(--color-accent-hover)] disabled:opacity-50"
        >
          {isPending ? "Generating…" : link ? "Generate a new link" : "Generate invite link"}
        </button>
      </div>
    </section>
  );
}

// A single boolean toggle auto-saves on change rather than needing an
// explicit Save button — the other two sections below use one since
// they involve picking from a list first, but there's nothing to "pick"
// here beyond flipping the switch itself. Defaults to on (matching the
// narration_enabled column's own default), since always-reading-aloud is
// the existing behavior this preserves for anyone who never visits this
// page. The recording screen itself also has its own override for
// switching this in the moment without coming here first — see
// record-interview-flow.tsx.
function NarrationToggleSettings({ narrationEnabled }: { narrationEnabled: boolean }) {
  const [enabled, setEnabled] = useState(narrationEnabled);
  const [isPending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);
  const [savedMessage, setSavedMessage] = useState<string | null>(null);

  function handleToggle(next: boolean) {
    setEnabled(next);
    setError(null);
    setSavedMessage(null);
    startTransition(async () => {
      const result = await setNarrationEnabled(next);
      if ("error" in result) {
        setError(result.error);
        return;
      }
      setSavedMessage(
        next ? "Saved — questions will be read aloud." : "Saved — questions will stay silent.",
      );
    });
  }

  return (
    <section className="flex flex-col gap-3 rounded-[var(--radius-lg)] border border-[color:var(--color-border)] bg-[color:var(--color-bg-surface)] p-6 shadow-[var(--shadow-2)]">
      <div>
        <h2 className="text-[length:var(--font-size-heading-3)] leading-[var(--line-height-heading-3)] font-semibold">
          Interview narration
        </h2>
        <p className="mt-1 text-sm text-[color:var(--color-text-secondary)]">
          Whether interview questions get read aloud during recording. On by default.
        </p>
      </div>

      <label className="flex items-center gap-2 text-sm">
        <input
          type="checkbox"
          checked={enabled}
          onChange={(e) => handleToggle(e.target.checked)}
          disabled={isPending}
        />
        🔊 Read questions aloud
      </label>

      {error && <p className="text-sm text-[color:var(--color-error)]">{error}</p>}
      {savedMessage && (
        <p className="text-sm text-[color:var(--color-success-subtle-fg)]">{savedMessage}</p>
      )}
    </section>
  );
}

function ThisIsMeSettings({
  people,
  personSummaries,
  linkedPersonId,
}: {
  people: Person[];
  personSummaries: Record<string, PersonSummary>;
  linkedPersonId: string | null;
}) {
  const [selectedId, setSelectedId] = useState<string | null>(linkedPersonId);
  const [isPending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);
  const [savedMessage, setSavedMessage] = useState<string | null>(null);

  const linkedPerson = linkedPersonId
    ? (people.find((p) => p.id === linkedPersonId) ?? null)
    : null;

  function save(personId: string | null) {
    setError(null);
    setSavedMessage(null);
    startTransition(async () => {
      const result = await setLinkedPerson(personId);
      if ("error" in result) {
        setError(result.error);
        return;
      }
      setSavedMessage(
        personId ? "Saved." : "Cleared — you're not linked to anyone in the tree.",
      );
    });
  }

  function handleNotInTree() {
    setSelectedId(null);
    save(null);
  }

  return (
    <section className="flex flex-col gap-4 rounded-[var(--radius-lg)] border border-[color:var(--color-border)] bg-[color:var(--color-bg-surface)] p-6 shadow-[var(--shadow-2)]">
      <div>
        <h2 className="text-[length:var(--font-size-heading-3)] leading-[var(--line-height-heading-3)] font-semibold">
          This is me
        </h2>
        <p className="mt-1 text-sm text-[color:var(--color-text-secondary)]">
          Link your account to your own record in the family tree. This is used to show your
          part of the tree by default when you open it.
        </p>
      </div>

      <p className="text-sm text-[color:var(--color-text-secondary)]">
        {linkedPerson ? (
          <>
            Currently linked to{" "}
            <strong className="text-[color:var(--color-text-primary)]">
              {linkedPerson.name}
            </strong>
            .
          </>
        ) : (
          "You're not linked to anyone in the tree yet."
        )}
      </p>

      <PersonSearch
        people={people}
        personSummaries={personSummaries}
        selectedId={selectedId}
        onSelect={setSelectedId}
        placeholder="Search for your name…"
      />

      {error && <p className="text-sm text-[color:var(--color-error)]">{error}</p>}
      {savedMessage && (
        <p className="text-sm text-[color:var(--color-success-subtle-fg)]">{savedMessage}</p>
      )}

      <div className="flex flex-wrap gap-2">
        <button
          type="button"
          onClick={() => save(selectedId)}
          disabled={isPending || selectedId === linkedPersonId}
          className="rounded-[var(--radius-sm)] bg-[color:var(--color-accent)] px-4 py-2 text-sm font-medium text-[color:var(--color-text-on-accent)] transition-colors duration-[var(--duration-base)] hover:bg-[color:var(--color-accent-hover)] disabled:opacity-50"
        >
          {isPending ? "Saving…" : "Save"}
        </button>
        <button
          type="button"
          onClick={handleNotInTree}
          disabled={isPending || (!selectedId && !linkedPersonId)}
          className="rounded-[var(--radius-sm)] border border-[color:var(--color-border)] px-4 py-2 text-sm transition-colors duration-[var(--duration-base)] hover:bg-[color:var(--color-bg-surface-hover)] disabled:opacity-50"
        >
          I&apos;m not in the tree yet
        </button>
      </div>
    </section>
  );
}

// A plain <select> of voice names means nothing to most people — hearing
// the actual difference before choosing is what matters, hence a
// "▶ Preview" button per row rather than a native dropdown. Filtered to
// English voices only, since that's what interview prompts are actually
// read in — the full getVoices() list can run into the hundreds once every
// language variant is counted (verified: 190 on a real Mac), and showing
// all of them here would bury the handful that are actually relevant.
// Further filtered to Google-named voices only — the non-Google entries on
// this platform (Trinoids, Whisper, Wobble, Zarvox, etc.) are either
// novelty voices or dated/robotic-sounding standard ones, same complaint
// PREFERRED_VOICE_NAMES's own comment already made about the equivalent
// non-Apple/non-Google options. Matched by substring on the voice name
// rather than an exact list of today's known Google voice names (Google US
// English, Google UK English Female/Male) — the exact set can vary by
// browser/OS, and a substring match keeps working on someone else's
// machine without needing to enumerate every variant.
function VoiceSettings({ interviewVoiceURI }: { interviewVoiceURI: string | null }) {
  const [voices, setVoices] = useState<SpeechSynthesisVoice[] | null>(null);
  const [selectedURI, setSelectedURI] = useState<string | null>(interviewVoiceURI);
  const [previewingURI, setPreviewingURI] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);
  const [savedMessage, setSavedMessage] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    getVoicesAsync().then((all) => {
      if (cancelled) return;
      setVoices(
        all.filter(
          (v) => v.lang.toLowerCase().startsWith("en") && v.name.toLowerCase().includes("google"),
        ),
      );
    });
    return () => {
      cancelled = true;
    };
  }, []);

  const defaultVoice = voices ? pickPreferredVoice(voices, null) : null;
  const selectedVoice = voices?.find((v) => v.voiceURI === selectedURI) ?? null;

  function handlePreview(voice: SpeechSynthesisVoice) {
    if (typeof window === "undefined" || typeof window.speechSynthesis === "undefined") return;
    window.speechSynthesis.cancel();
    const utterance = new SpeechSynthesisUtterance(
      "Hi, I'm going to be reading your interview questions aloud, just like this.",
    );
    utterance.voice = voice;
    setPreviewingURI(voice.voiceURI);
    const clear = () => setPreviewingURI((current) => (current === voice.voiceURI ? null : current));
    utterance.onend = clear;
    utterance.onerror = clear;
    window.speechSynthesis.speak(utterance);
  }

  function save(voiceURI: string | null) {
    setError(null);
    setSavedMessage(null);
    startTransition(async () => {
      const result = await setInterviewVoice(voiceURI);
      if ("error" in result) {
        setError(result.error);
        return;
      }
      setSavedMessage(
        voiceURI ? "Saved." : "Cleared — the default voice will be used.",
      );
    });
  }

  function handleUseDefault() {
    setSelectedURI(null);
    save(null);
  }

  return (
    <section className="flex flex-col gap-4 rounded-[var(--radius-lg)] border border-[color:var(--color-border)] bg-[color:var(--color-bg-surface)] p-6 shadow-[var(--shadow-2)]">
      <div>
        <h2 className="text-[length:var(--font-size-heading-3)] leading-[var(--line-height-heading-3)] font-semibold">
          Narration voice
        </h2>
        <p className="mt-1 text-sm text-[color:var(--color-text-secondary)]">
          Choose which voice reads interview questions aloud. Preview a voice before picking it —
          a name alone won&apos;t tell you much.
        </p>
      </div>

      <p className="text-sm text-[color:var(--color-text-secondary)]">
        {selectedVoice ? (
          <>
            Currently set to{" "}
            <strong className="text-[color:var(--color-text-primary)]">{selectedVoice.name}</strong>.
          </>
        ) : selectedURI ? (
          "Currently set to a voice that isn't available on this device — the default will be used here instead."
        ) : (
          <>
            No preference set — using the default voice
            {defaultVoice ? (
              <>
                : <strong className="text-[color:var(--color-text-primary)]">{defaultVoice.name}</strong>
              </>
            ) : (
              ""
            )}
            .
          </>
        )}
      </p>

      {voices === null ? (
        <p className="text-sm text-[color:var(--color-text-secondary)]">Loading available voices…</p>
      ) : voices.length === 0 ? (
        <p className="text-sm text-[color:var(--color-text-secondary)]">
          No voices available in this browser — narration will fall back to on-screen text only.
        </p>
      ) : (
        <div className="flex max-h-64 flex-col gap-0.5 overflow-y-auto rounded-[var(--radius-sm)] border border-[color:var(--color-border)] p-2">
          {voices.map((voice) => (
            <div
              key={voice.voiceURI}
              className="flex items-center justify-between gap-2 rounded-[var(--radius-xs)] px-2 py-1.5 text-sm hover:bg-[color:var(--color-bg-surface-hover)]"
            >
              <label className="flex flex-1 items-center gap-2">
                <input
                  type="radio"
                  name="interview-voice"
                  checked={selectedURI === voice.voiceURI}
                  onChange={() => setSelectedURI(voice.voiceURI)}
                />
                <span>{voice.name}</span>
                <span className="text-xs text-[color:var(--color-text-tertiary)]">{voice.lang}</span>
                {voice.default && (
                  <span className="text-xs text-[color:var(--color-text-tertiary)]">
                    (device default)
                  </span>
                )}
              </label>
              <button
                type="button"
                onClick={() => handlePreview(voice)}
                disabled={previewingURI === voice.voiceURI}
                className="shrink-0 rounded-[var(--radius-sm)] border border-[color:var(--color-border)] px-2 py-0.5 text-xs transition-colors duration-[var(--duration-base)] hover:bg-[color:var(--color-bg-surface-hover)] disabled:opacity-50"
              >
                {previewingURI === voice.voiceURI ? "▶ Playing…" : "▶ Preview"}
              </button>
            </div>
          ))}
        </div>
      )}

      {error && <p className="text-sm text-[color:var(--color-error)]">{error}</p>}
      {savedMessage && (
        <p className="text-sm text-[color:var(--color-success-subtle-fg)]">{savedMessage}</p>
      )}

      <div className="flex flex-wrap gap-2">
        <button
          type="button"
          onClick={() => save(selectedURI)}
          disabled={isPending || selectedURI === interviewVoiceURI}
          className="rounded-[var(--radius-sm)] bg-[color:var(--color-accent)] px-4 py-2 text-sm font-medium text-[color:var(--color-text-on-accent)] transition-colors duration-[var(--duration-base)] hover:bg-[color:var(--color-accent-hover)] disabled:opacity-50"
        >
          {isPending ? "Saving…" : "Save"}
        </button>
        <button
          type="button"
          onClick={handleUseDefault}
          disabled={isPending || (!selectedURI && !interviewVoiceURI)}
          className="rounded-[var(--radius-sm)] border border-[color:var(--color-border)] px-4 py-2 text-sm transition-colors duration-[var(--duration-base)] hover:bg-[color:var(--color-bg-surface-hover)] disabled:opacity-50"
        >
          Use default instead
        </button>
      </div>
    </section>
  );
}

// Stage 2's second entry point (the first is the home page's zero-family
// state, for a brand-new signup with no invite code) — this one is for
// an already-logged-in user starting a genuinely separate, independent
// second family, not adding anyone to their existing one (that's "Invite
// someone" above). create_family() makes the new family active, so this
// navigates away from Settings on success (see CreateFamilyForm) rather
// than staying put showing a saved-message — Settings itself is now
// showing the OLD family's data underneath, which would be misleading to
// leave on screen once the active family has actually changed.
function CreateFamilySettings() {
  return (
    <section className="flex flex-col gap-4 rounded-[var(--radius-lg)] border border-[color:var(--color-border)] bg-[color:var(--color-bg-surface)] p-6 shadow-[var(--shadow-2)]">
      <div>
        <h2 className="text-[length:var(--font-size-heading-3)] leading-[var(--line-height-heading-3)] font-semibold">
          Start a new family tree
        </h2>
        <p className="mt-1 text-sm text-[color:var(--color-text-secondary)]">
          Create a separate, independent family tree — for example, to research a different
          branch of your family. This doesn&apos;t affect your current family or its data.
        </p>
      </div>
      <CreateFamilyForm />
    </section>
  );
}

// Distinct from "Start a new family tree" above (an empty new family) —
// this copies everything already in the current family. See
// ForkFamilyForm for the confirmation flow itself; this section just
// supplies the surrounding heading/description, matching every other
// section's shell.
function ForkFamilySettings() {
  return (
    <section className="flex flex-col gap-4 rounded-[var(--radius-lg)] border border-[color:var(--color-border)] bg-[color:var(--color-bg-surface)] p-6 shadow-[var(--shadow-2)]">
      <div>
        <h2 className="text-[length:var(--font-size-heading-3)] leading-[var(--line-height-heading-3)] font-semibold">
          Fork this family
        </h2>
        <p className="mt-1 text-sm text-[color:var(--color-text-secondary)]">
          Make a complete, independent copy of everything in this family tree — people,
          documents, interviews, facts, and stories — under a new name, so you can branch off
          and edit freely without affecting the original.
        </p>
      </div>
      <ForkFamilyForm />
    </section>
  );
}

// Stage 4: only rendered when the account has more than one family
// (SettingsView's families.length > 1 check) — a single-family user, the
// common case, sees no change here. Reuses setActiveFamily rather than
// any new mechanism; on success there's no client-side redirect because
// Next.js already refreshes this page's own server data as part of the
// action response (the same behavior that made get_invite_preview's
// check order matter in Stage 1), so this list and every other
// family-scoped section on the page pick up the new active family
// automatically.
function FamilySwitcherSettings({ families }: { families: FamilyMembership[] }) {
  const [isPending, startTransition] = useTransition();
  const [switchingId, setSwitchingId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  function handleSwitch(familyId: string) {
    setError(null);
    setSwitchingId(familyId);
    startTransition(async () => {
      const result = await setActiveFamily(familyId);
      setSwitchingId(null);
      if ("error" in result) {
        setError(result.error);
      }
    });
  }

  return (
    <section className="flex flex-col gap-4 rounded-[var(--radius-lg)] border border-[color:var(--color-border)] bg-[color:var(--color-bg-surface)] p-6 shadow-[var(--shadow-2)]">
      <div>
        <h2 className="text-[length:var(--font-size-heading-3)] leading-[var(--line-height-heading-3)] font-semibold">
          Your family trees
        </h2>
        <p className="mt-1 text-sm text-[color:var(--color-text-secondary)]">
          You belong to more than one family tree. Switch which one is active — the rest of the
          app (tree, documents, interviews, and everything else here) always reflects whichever
          one is active.
        </p>
      </div>
      <ul className="flex flex-col gap-2">
        {families.map((family) => (
          <li
            key={family.id}
            className="flex items-center justify-between gap-3 rounded-[var(--radius-sm)] border border-[color:var(--color-border)] px-3 py-2"
          >
            <span className="text-sm text-[color:var(--color-text-primary)]">
              {family.name}
              {family.isActive && (
                <span className="ml-2 rounded-[var(--radius-xs)] bg-[color:var(--color-success-subtle-bg)] px-2 py-0.5 text-[10px] font-medium uppercase tracking-wide text-[color:var(--color-success-subtle-fg)]">
                  Active
                </span>
              )}
            </span>
            {!family.isActive && (
              <button
                type="button"
                onClick={() => handleSwitch(family.id)}
                disabled={isPending}
                className="rounded-[var(--radius-sm)] border border-[color:var(--color-border)] px-3 py-1 text-xs transition-colors duration-[var(--duration-base)] hover:bg-[color:var(--color-bg-surface-hover)] disabled:opacity-50"
              >
                {switchingId === family.id ? "Switching…" : "Switch"}
              </button>
            )}
          </li>
        ))}
      </ul>
      {error && <p className="text-sm text-[color:var(--color-error)]">{error}</p>}
    </section>
  );
}
